DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

DROP TABLE IF EXISTS shopping_list;
CREATE TABLE IF NOT EXISTS shopping_list (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    item_price DECIMAL(10,2) NOT NULL,
    item_category grocery NOT NULL,
    item_checked BOOLEAN DEFAULT FALSE NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL 
);